server:
  port: 7000

# database resource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_mysql?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# integrate mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
